#ticket.csv.pathRemoli=/Users/simoneremoli/IdeaProjects/RouteX_MVC_Project/FilePersistenza/Tickets_sync.csv
ticket.csv.pathBrondi=C:/Users/loren/Desktop/Università/ISPW/Progetto/RouteXEsame/FilePersistenza/Tickets_sync.csv
