#ticket.csv.pathRemoli=/Users/simoneremoli/IdeaProjects/RouteX_MVC_Project/FilePersistenza/Tickets_sync.csv
ticket.csv.pathBrondi=\Users\loren\Desktop\Università\ISPW\Progetto\RouteXEsame\FilePersistenzaTickets_sync.csv
